version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: "postgres"
    hostname: pg.server
    restart: always
    environment:
      - "POSTGRES_DB=$DB_NAME"
      - "POSTGRES_USER=$DB_USER"
      - "POSTGRES_PASSWORD=$DB_PASS"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_vol:/var/lib/postgresql/data"
  redis:
    image: redis
    container_name: "redis"
    hostname: redis.server
    restart: always
    command: [
        "redis-server",
        "--appendonly yes",
    ]
    ports:
      - "6379:6379"
    volumes:
      - "db_redis_vol:/data"
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    hostname: traefik.server
    environment:
      - "CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}"
      - "CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53,1.0.0.1:53"
      - "--certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=20"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_vol:/data"
  website:
    image: haakco/stage3-ubuntu-20.04-php7.4-lv-docker
    container_name: "web"
    hostname: web.server
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`$DOMAIN_NAME`,`www.$DOMAIN_NAME`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls=true"
      - "traefik.http.routers.website.tls.certresolver=le"
    environment:
      - GEN_LV_ENV=TRUE
      - LVENV_APP_NAME=Wave
      - LVENV_APP_ENV=local
      - LVENV_APP_KEY=$APP_KEY
      - LVENV_APP_DEBUG=true
      - LVENV_APP_LOG_LEVEL=debug
      - LVENV_APP_URL=https://dev.$DOMAIN_NAME
      - LVENV_DB_CONNECTION=pgsql
      - LVENV_DB_HOST=postgres
      - LVENV_DB_PORT=5432
      - LVENV_DB_DATABASE=$DB_NAME
      - LVENV_DB_USERNAME=$DB_USER
      - LVENV_DB_PASSWORD=$DB_PASS
      - LVENV_BROADCAST_DRIVER=log
      - LVENV_CACHE_DRIVER=redis
      - LVENV_SESSION_DRIVER=redis
      - LVENV_SESSION_LIFETIME=9999
      - LVENV_QUEUE_DRIVER=sync
      - LVENV_REDIS_HOST=redis.server
      - LVENV_REDIS_PASSWORD=null
      - LVENV_REDIS_PORT=6379
      - LVENV_MAIL_DRIVER=smtp
      - LVENV_MAIL_HOST=smtp.mailtrap.io
      - LVENV_MAIL_PORT=2525
      - LVENV_MAIL_USERNAME=
      - LVENV_MAIL_PASSWORD=
      - LVENV_MAIL_ENCRYPTION=null
      - LVENV_PUSHER_APP_ID=
      - LVENV_PUSHER_APP_KEY=
      - LVENV_PUSHER_APP_SECRET=
      - LVENV_JWT_SECRET=$JWT_SECRET
      - LVENV_PADDLE_VENDOR_ID=
      - LVENV_PADDLE_VENDOR_AUTH_CODE=
      - LVENV_PADDLE_ENV=sandbox
      - LVENV_WAVE_DOCS=true
      - LVENV_WAVE_DEMO=true
      - LVENV_WAVE_BAR=true
    ports:
      - "9080:9080"
    volumes:
      - "${PWD}/wave/:/var/www/site"
volumes:
  postgres_vol: {}
  db_redis_vol: {}
  traefik_vol: {}
