---
- hosts: all
  vars:
    bootstrap: true
    ansible_user: root
    domain_name: example.com
    letsencrypt_email: certbot@example.com
    php_ver: 7.4
  roles:
    - upgrade_server
    - docker
  become: true
  gather_facts: true
