---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wave-cert-prod
spec:
  commonName: custd.com
  secretName: wave-cert-prod-tls
  dnsNames:
    - custd.com
    - www.custd.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
